class dashboardPage {
    login = '.form-inline > .navbar-nav > :nth-child(2) > .nav-link'
    username = '#Username'
    password = '#Password'
    login_button = '.btn-primary'
    clear_button = ':nth-child(7) > :nth-child(2) > .btn-secondary'
    success_login = 'h3'
    logout = '.form-inline > .navbar-nav > :nth-child(2) > .nav-link'
    wording_cust = 'h2'
    create_button = ':nth-child(4) > .btn'
    search_bar = '#searching'
    search_input = '.container > div > form > .btn'
    cust_name = '#Name'
    cust_company = '#Company'
    cust_address = '#Address'
    cust_city = '#City'
    cust_phone = '#Phone'
    cust_email = '#Email'
    create_cust_button = '.col-md-offset-2 > .btn'
    table = '.table'
    contain_name_table = 'tbody > :nth-child(2) > :nth-child(1)'
    contain_email_table = 'tbody > :nth-child(2) > :nth-child(6)'
    edit_button = ':nth-child(2) > :nth-child(7) > .btn-outline-primary'
    detail_button = ':nth-child(2) > :nth-child(7) > .btn-outline-info'
    delete_button = ':nth-child(2) > :nth-child(7) > .btn-outline-danger'
    detail = 'h4'
    detail_name = '.dl-horizontal > :nth-child(1)'
    detail_name_contain = '.dl-horizontal > :nth-child(2)'
    detail_company = '.dl-horizontal > :nth-child(3)'
    detail_company_contain = '.dl-horizontal > :nth-child(4)'
    detail_address = '.dl-horizontal > :nth-child(5)'
    detail_address_contain = '.dl-horizontal > :nth-child(6)'
    detail_city = ':nth-child(7)'
    detail_city_contain = ':nth-child(8)'
    detail_phone = ':nth-child(9)'
    detail_phone_contain = ':nth-child(10)'
    detail_email = ':nth-child(11)'
    detail_email_contain = ':nth-child(12)'
    detail_edit_button = '.btn-outline-primary'
    detail_back_button = '.btn-link'
}

export default dashboardPage;