Cypress.on('uncaught:exception', (err, runnable) => {
    return false
  })

import dashboardPage from "../../support/dashboard-page"
const dashboardInput = require('../../fixtures/data.json')
const dayjs = require("dayjs");
  
describe('Dashboard Itera', () => {
    const Timenow24hours = dayjs().format("H:mm:ss");
    const DashboardPage = new dashboardPage()
    it('dashboard', () => {
      cy.visit('/')
      cy.get(DashboardPage.login).click()
      cy.url().should('include', '/Login')
      cy.get(DashboardPage.username).type(dashboardInput.static_username)
      cy.get(DashboardPage.password).type(dashboardInput.password)
      cy.get(DashboardPage.login_button).click()
      //cy.get('form').submit()
      cy.get(DashboardPage.success_login)
        .contains('Welcome '+ dashboardInput.static_username)
        .should('match', 'h3')
      cy.get(DashboardPage.logout).as('links')
        .should('have.class', 'nav-link')
        .and('have.attr', 'href')
        .and('include', 'LogOut')
      cy.get(DashboardPage.wording_cust)
        .should('have.text', 'Customer Details')
      cy.get(DashboardPage.create_button).as('links')
        .should('have.class', 'btn btn-primary')
        .and('have.attr', 'href')
        .and('include', 'Create')
      cy.get(DashboardPage.search_bar)
        .should('have.id', 'searching')
        .and('have.attr', 'name', 'searching')
        .and('have.attr', 'placeholder', 'Search Name or Email')
        //.and('be.a', 'string')
        .invoke('text')
      cy.get(DashboardPage.search_input)
        .should('have.class', 'btn btn-secondary my-2 my-sm-0')
        .and('have.value', 'Search')
        .and('have.attr', 'type', 'submit')
    }) 
    it('create customer', () => {
        cy.visit('/')
        cy.get(DashboardPage.login).click()
        cy.url().should('include', '/Login')
        cy.get(DashboardPage.username).type(dashboardInput.static_username)
        cy.get(DashboardPage.password).type(dashboardInput.password)
        cy.get(DashboardPage.login_button).click()
        cy.get(DashboardPage.success_login)
          .contains('Welcome '+ dashboardInput.static_username)
          .should('match', 'h3')
        cy.get(DashboardPage.create_button).click()
        cy.url().should('include', '/Customer/Create')
        cy.get(DashboardPage.cust_name).type(dashboardInput.cust_name + Timenow24hours)
          .should('have.id', 'Name')
          .and('have.attr', "name", "Name")
          .and('have.attr', 'type', 'text')
        cy.get(DashboardPage.cust_company).type(dashboardInput.cust_company)
          .should('have.id', 'Company')
          .and('have.attr', "name", "Company")
          .and('have.attr', 'type', 'text')
        cy.get(DashboardPage.cust_address).type(dashboardInput.cust_address)
          .should('have.id', 'Address')
          .and('have.attr', "name", "Address")
          .and('have.attr', 'type', 'text')
        cy.get(DashboardPage.cust_city).type(dashboardInput.cust_city)
          .should('have.id', 'City')
          .and('have.attr', "name", "City")
          .and('have.attr', 'type', 'text')
        cy.get(DashboardPage.cust_phone).type(dashboardInput.cust_phone)
          .should('have.id', 'Phone')
          .and('have.attr', "name", "Phone")
          .and('have.attr', 'type', 'text')
        cy.get(DashboardPage.cust_email).type(dashboardInput.cust_email)
          .should('have.id', 'Email')
          .and('have.attr', "name", "Email")
          .and('have.attr', 'type', 'text')
        cy.get(DashboardPage.create_cust_button)
          .should('have.class', 'btn btn-primary')
          .and('have.attr', 'type', 'submit')
          .and('have.value', 'Create')
          .click()
        cy.url().should('include', '/Dashboard')
    }) 
    it('search name', () => {
      cy.visit('/')
      cy.get(DashboardPage.login).click()
      cy.url().should('include', '/Login')
      cy.get(DashboardPage.username).type(dashboardInput.static_username)
      cy.get(DashboardPage.password).type(dashboardInput.password)
      cy.get(DashboardPage.login_button).click()
      //cy.get('form').submit()
      cy.get(DashboardPage.success_login)
        .contains('Welcome '+ dashboardInput.static_username)
        .should('match', 'h3')
      cy.get(DashboardPage.wording_cust)
        .should('have.text', 'Customer Details')
      cy.get(DashboardPage.search_bar)
        .should('have.id', 'searching')
        .and('have.attr', 'name', 'searching')
        .and('have.attr', 'placeholder', 'Search Name or Email')
        .type(dashboardInput.cust_name)
      cy.get(DashboardPage.search_input)
        .should('have.class', 'btn btn-secondary my-2 my-sm-0')
        .and('have.value', 'Search')
        .and('have.attr', 'type', 'submit')
        .click()
      cy.get(DashboardPage.table)
        .find('tbody tr')
        .first()
        .should('have.class', 'table-primary')
      cy.get(DashboardPage.contain_name_table)
        .should('contain', dashboardInput.cust_name)
    }) 
    it('search email', () => {
      cy.visit('/')
      cy.get(DashboardPage.login).click()
      cy.url().should('include', '/Login')
      cy.get(DashboardPage.username).type(dashboardInput.static_username)
      cy.get(DashboardPage.password).type(dashboardInput.password)
      cy.get(DashboardPage.login_button).click()
      //cy.get('form').submit()
      cy.get(DashboardPage.success_login)
        .contains('Welcome '+ dashboardInput.static_username)
        .should('match', 'h3')
      cy.get(DashboardPage.wording_cust)
        .should('have.text', 'Customer Details')
      cy.get(DashboardPage.search_bar)
        .should('have.id', 'searching')
        .and('have.attr', 'name', 'searching')
        .and('have.attr', 'placeholder', 'Search Name or Email')
        .type(dashboardInput.cust_email)
      cy.get(DashboardPage.search_input)
        .should('have.class', 'btn btn-secondary my-2 my-sm-0')
        .and('have.value', 'Search')
        .and('have.attr', 'type', 'submit')
        .click()
      cy.get(DashboardPage.table)
        .find('tbody tr')
        .first()
        .should('have.class', 'table-primary')
      cy.get(DashboardPage.contain_email_table)
        //.should('contain', dashboardInput.cust_email)
        .should('contain', 'shin.ryujin')
    }) 
    it.only('click button detail', () => {
      cy.visit('/')
      cy.get(DashboardPage.login).click()
      cy.url().should('include', '/Login')
      cy.get(DashboardPage.username).type(dashboardInput.static_username)
      cy.get(DashboardPage.password).type(dashboardInput.password)
      cy.get(DashboardPage.login_button).click()
      //cy.get('form').submit()
      cy.get(DashboardPage.success_login)
        .contains('Welcome '+ dashboardInput.static_username)
        .should('match', 'h3')
      cy.get(DashboardPage.wording_cust)
        .should('have.text', 'Customer Details')
      cy.get(DashboardPage.detail_button)
        .and('have.attr', 'href', '/Customer/Details/4150')
        .click()
      cy.url().should('eq', 'https://itera-qa.azurewebsites.net/Customer/Details/4150')
      cy.get(DashboardPage.wording_cust)
        .should('have.text', 'Details')
      cy.get(DashboardPage.detail)
        .should('have.text', 'Customer')
      cy.get(DashboardPage.detail_name)
        .should('contain.html', dashboardInput.detail_name)
        .invoke('text')
      cy.get(DashboardPage.detail_name_contain)
        .should('contain.html', dashboardInput.detail_name_contain)
        .invoke('text')
      cy.get(DashboardPage.detail_company)
        .should('contain.html', dashboardInput.detail_company)
        .invoke('text')
      cy.get(DashboardPage.detail_company_contain)
        .should('contain.html', dashboardInput.detail_company_contain)
        .invoke('text')
      cy.get(DashboardPage.detail_address)
        .invoke('text')
      cy.get(DashboardPage.detail_address_contain)
        .should('contain.html', dashboardInput.detail_address_contain)
        .invoke('text')
      cy.get(DashboardPage.detail_city)
        .should('contain.html', dashboardInput.detail_city)
        .invoke('text')
      cy.get(DashboardPage.detail_city_contain)
        .should('contain.html', dashboardInput.detail_city_contain)
        .invoke('text')
      cy.get(DashboardPage.detail_phone)
        .should('contain.html', dashboardInput.detail_phone)
        .invoke('text')
      cy.get(DashboardPage.detail_phone_contain)
        .should('contain.html', dashboardInput.detail_phone_contain)
        .invoke('text')
      cy.get(DashboardPage.detail_email)
        .should('contain.html', dashboardInput.detail_email)
        .invoke('text')
      cy.get(DashboardPage.detail_email_contain)
        .should('contain.html', dashboardInput.detail_email_contain)
        .invoke('text')
      cy.get(DashboardPage.detail_edit_button)
        .and('have.attr', 'href', '/Customer/Edit/4150')
        .should('contain.html', dashboardInput.detail_edit_button)
      cy.get(DashboardPage.detail_back_button)
        .and('have.attr', 'href', '/Dashboard')
        .should('contain.html', dashboardInput.detail_back_button)
    }) 
})